argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  repoServer:
    volumeMounts:
      - mountPath: /usr/local/bin/helm
        name: helm-tools
        subPath: helm
      - mountPath: /usr/local/bin/helm-original
        name: helm-tools
        subPath: helm-original
    volumes:
      - name: helm-tools
        emptyDir: {}
      - name: helm-wrapper
        configMap:
          name: helm-wrapper
    initContainers:
      - name: wrap-helm
        image: alpine
        command: [sh, -c]
        args:
          - >-
            set -x;
            cd /helm-tools &&
            wget -qO- https://get.helm.sh/helm-v3.15.4-linux-amd64.tar.gz | tar -xvzf - &&
            mv linux-amd64/helm /helm-tools/helm-original &&
            cp /helm/helm /helm-tools/helm &&
            chmod +x /helm-tools/helm
        volumeMounts:
          - name: helm-wrapper
            mountPath: /helm
          - name: helm-tools
            mountPath: /helm-tools
  server:
    extraArgs:
      - --insecure
  config:
    params:
      server:
        insecure: true
